### ISSUE TITLE
Can't use the template as intended

### ISSUE THREAD

**Issue by tshirtman** [maltfield/cross-platform-python-gui#3]
Clicking the "use this template" button i get an error.

![image](https://user-images.githubusercontent.com/22759/91912548-b482e600-ecb3-11ea-9ef7-adba0761b7ac.png)
```

We're sorry, something went wrong.

We were unable to clone maltfield/cross-platform-python-gui's contents into tshirtman/test-crossplatform-kivy-packaging. The template you used includes files that are larger than 10 megabytes. Please ask maltfield to remove those files from the template and try again.
```

Didn't look into which files where problematic and how necessary they are, but it's blocking the intended use :(

**Comment by maltfield** [comment]
@tshirtman thanks for the report

Does the same issue happen when you create a fork instead of clicking the "use this template" button?

**Comment by maltfield** [comment]
So there's one non-`.git` file that is >10 MB

```
user@buskill:~/sandbox/cross-platform-python-gui$ find -size +1M -exec du -sh '{}' \; | grep -vi .git
1.9M	./build/deps/appimagetool-x86_64.AppImage
17M	./build/deps/python3.7.8-cp37-cp37m-manylinux2014_x86_64.AppImage
user@buskill:~/sandbox/cross-platform-python-gui$ 
```

I didn't originally have these files in this repo (originally they were downloaded at build-time), but these python AppImages are released on GitHub, and they're apparently automatically deleted after some time, which has caused this repo's build scripts to break in the past.

Rather than be dependent on external dependencies that will eventually 404, I decided to store these dependencies directly in the repo.

 * https://github.com/maltfield/cross-platform-python-gui/commit/be7c8dbc03e8f0f3853905717a4299f7a4e35e7f

This seems like a really dumb GitHub restriction for templates. Please use the "fork" method instead.

**Comment by tshirtman** [comment]
Sorry for not getting back to you earlier, indeed, it works after cloning and enabling the workflows, just tested the appImage on linux, and it works perfectly, thanks a lot for this work.
